"""empty message

Revision ID: 847c8b8cb9e9
Revises: 
Create Date: 2021-06-09 11:37:59.375416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847c8b8cb9e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('prefix', sa.String(length=3), nullable=True),
    sa.Column('announcements_channel_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('moderation_channel_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('welcome_channel_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('coins', sa.BigInteger(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('hide_age', sa.Boolean(), nullable=True),
    sa.Column('hide_birthday', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('greetings_phrases',
    sa.Column('short_code', sa.String(length=8), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('phrase', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('short_code', 'server_id'),
    sa.UniqueConstraint('server_id', 'phrase')
    )
    op.create_index(op.f('ix_greetings_phrases_server_id'), 'greetings_phrases', ['server_id'], unique=False)
    op.create_table('servermembers',
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('exp', sa.BigInteger(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('ban_counter', sa.Integer(), nullable=True),
    sa.Column('kick_counter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'server_id')
    )
    op.create_index(op.f('ix_servermembers_member_id'), 'servermembers', ['member_id'], unique=False)
    op.create_index(op.f('ix_servermembers_server_id'), 'servermembers', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servermembers_server_id'), table_name='servermembers')
    op.drop_index(op.f('ix_servermembers_member_id'), table_name='servermembers')
    op.drop_table('servermembers')
    op.drop_index(op.f('ix_greetings_phrases_server_id'), table_name='greetings_phrases')
    op.drop_table('greetings_phrases')
    op.drop_table('users')
    op.drop_table('servers')
    # ### end Alembic commands ###
